language: scala
sudo: required
jdk:
    - oraclejdk7
    - oraclejdk8
scala:
    - 2.11.2
    - 2.11.6
branches:
  only:
    - master
    - 0.4.0-dev
script: "sbt clean coverage test"
after_success: "sbt coveralls"

