language: scala
sudo: required
jdk:
    - oraclejdk7
    - oraclejdk8
scala:
    - 2.11.2
    - 2.11.6
branches:
  only:
    - master
script:
    - sbt clean coverage test &&
      sbt coverageAggregate
after_success:
    - sbt coveralls


